name: Flow cleanup

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  flow_cleanup:
    runs-on: ubicloud-standard-2-ubuntu-2204-arm
    timeout-minutes: 60
    steps:
      - name: checkout sources
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
          cache-dependency-path: e2e_cleanup/go.sum

      - name: download go modules
        run: |
          go mod download
        working-directory: ./e2e_cleanup
